### ISSUE TITLE
pagination needed to reduce load time

### ISSUE THREAD

**Issue by sheldonhull** [nehalist/ghoststa#1]
Looks like when I first pulled in this theme it had every post on the main page, resulting in 10 sec + load time. Not sure of the correct way to modify and update since pagination.hbs was included in partials. Any idea?

**Comment by nehalist** [comment]
Just tested this with the last version of Ghost and encountered no problems, pagination works fine. Are you sure your settings for `Posts per page` in your admin are correct?

**Comment by sheldonhull** [comment]
Yes. I have it set to 15. This theme loaded all on the home page

**Comment by nehalist** [comment]
That's weird. What version of Ghost and ghoststa are you using?

**Comment by sheldonhull** [comment]
latest version of Ghosta (as of yesterday) and Ghost 0.9 (latest)

**Comment by nehalist** [comment]
And you haven't modified the theme in any way? I can do more testing over the weekend, but I'm not really sure where to start, since everything works fine for me :/

**Comment by sheldonhull** [comment]
No problem. I'm using a custom theme right now and will probably stick with it for now. I was hoping to do a github style blog theme, with the simplified tags you implemented. 

I haven't customized any other basic setting to my knowledge. 
I'll mark as closed, but will watch for any theme updates. Thanks for your contributions to the ghost community.
