### ISSUE TITLE
theme problem

### ISSUE THREAD

**Issue by ubuntutest** [nehalist/ghoststa#3]
I'm getting the following error from console
`GET https://*****/assets/vendor/vendor.css?v=b565729596 
(index):171 GET https://*****/assets/vendor/vendor.js?v=b565729596 
(index):171 GET https://*****/assets/vendor/vendor.js?v=b565729596 404 (Not Found)
index.js?v=b565729596:1 Uncaught ReferenceError: $ is not defined
    at index.js?v=b565729596:1
(anonymous) @ index.js?v=b565729596:1`

There is no vendor.js and vendor.css file 
Theme dont works

**Comment by nehalist** [comment]
Vendor files weren't in the repo. I [actually wanted to fix that](https://github.com/nehalist/ghoststa/issues/2) in december, but totally forget about it. But nvm, it's fixed now.
