### ISSUE TITLE
Demo site is not available, and "SSL Required" is shown up

### ISSUE THREAD

**Issue by jingsong-liu** [nehalist/ghoststa#7]
Demo site in the readme.md is not available, and it show "SSL Required."
My browser is chrome in latest version.

**Comment by nehalist** [comment]
Oh, thanks for reporting! Will take care of it asap.

**Comment by dausruddin** [comment]
Emm.. Still down.

**Comment by nehalist** [comment]
Seems like i need to completely re-install ghost for the demo. Not a bad idea at all, since the demo was running on some  I'll hopefully find time for that this weekend.

And sorry for it to take that long... I'm pretty busy at the moment..

**Comment by nehalist** [comment]
Well, I found some time this evening... everything should be back to normal again. (And with https!)
